// <auto-generated/>
// Suppress CA1812 for ASP.NET Core types instantiated by DI or framework
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Instantiated by ASP.NET Core runtime or dependency injection.", Scope = "module")]
